const express = require('express');
const c = require('../controllers/extended.controller');
const { requireAuth } = require('../middleware/auth.middleware');
const router = express.Router(); router.use(requireAuth);
router.patch('/workspaces/:workspaceId/members/:userId', c.updateMemberRole);
router.delete('/workspaces/:workspaceId/members/:userId', c.removeMember);
router.post('/workspaces/:workspaceId/leave', c.leaveWorkspace);
router.route('/workspaces/:workspaceId/invitations').get(c.listInvitations).post(c.invite);
router.get('/invitations/mine', c.listMyInvitations); router.delete('/invitations/:invitationId', c.cancelInvitation); router.post('/invitations/accept', c.acceptInvitation); router.post('/invitations/:invitationId/accept', c.acceptInvitationById); router.post('/workspaces/join-code', c.joinWorkspaceByCode);
router.route('/projects/:projectId/flows').get(c.listFlows).post(c.createFlow); router.route('/flows/:flowId').patch(c.updateFlow).delete(c.removeFlow); router.post('/flows/:flowId/run', c.runFlowNow);
router.get('/projects/:projectId/executions', c.listExecutions);
router.route('/projects/:projectId/documents').get(c.listDocuments).post(c.createDocument); router.route('/documents/:documentId').patch(c.updateDocument).delete(c.deleteDocument);
router.route('/projects/:projectId/mocks').get(c.listMocks).post(c.createMock); router.route('/mocks/:mockId').patch(c.updateMock).delete(c.deleteMock); router.post('/mocks/:mockId/routes', c.addMockRoute); router.delete('/mock-routes/:mockRouteId', c.deleteMockRoute);
router.route('/projects/:projectId/datasets').get(c.listDatasets).post(c.createDataset); router.route('/datasets/:datasetId').patch(c.updateDataset).delete(c.deleteDataset); router.post('/datasets/:datasetId/run', c.runDataset);
module.exports = router;
