const express = require('express');
const c = require('../controllers/resource.controller');
const { requireAuth } = require('../middleware/auth.middleware');
const router = express.Router();
router.use(requireAuth);
router.route('/workspaces').get(c.listWorkspaces).post(c.createWorkspace);
router.route('/workspaces/:workspaceId').get(c.getWorkspace).patch(c.updateWorkspace).delete(c.removeWorkspace);
router.route('/workspaces/:workspaceId/projects').get(c.listProjects).post(c.createProject);
router.route('/projects/:projectId').get(c.getProject).patch(c.updateProject).delete(c.removeProject);
router.route('/projects/:projectId/collections').get(c.listCollections).post(c.createCollection);
router.route('/collections/:collectionId').patch(c.updateCollection).delete(c.removeCollection);
router.route('/collections/:collectionId/requests').get(c.listRequests).post(c.createRequest);
router.route('/requests/:requestId').patch(c.updateRequest).delete(c.removeRequest);
router.route('/projects/:projectId/environments').get(c.listEnvironments).post(c.createEnvironment);
router.route('/environments/:environmentId/secrets').get(c.listSecrets).post(c.createSecret);
router.delete('/secrets/:secretId', c.removeSecret);
router.route('/projects/:projectId/api-keys').get(c.listApiKeys).post(c.createApiKey);
router.delete('/api-keys/:apiKeyId', c.revokeApiKey);
module.exports = router;
